# Generated by Django 4.1.3 on 2022-12-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200, null=True, verbose_name='Driver Name')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Email')),
                ('vehicle_num_plate', models.CharField(max_length=200, null=True, verbose_name='Number Plate')),
            ],
        ),
        migrations.CreateModel(
            name='Sacco_Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Offial Name')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Email')),
                ('Department', models.CharField(max_length=200, null=True, verbose_name='Department Name')),
                ('Position', models.CharField(max_length=200, null=True, verbose_name='Office Position')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_date', models.DateTimeField(verbose_name='Schedule Date')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('manager', models.CharField(max_length=60, verbose_name='Manager')),
                ('driver_name', models.CharField(max_length=60, verbose_name='Driver Name')),
                ('vehicle_num_plate', models.CharField(max_length=60, verbose_name='Number Plate')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_num_plate', models.CharField(max_length=200, null=True, verbose_name='Number Plate')),
                ('driver_name', models.CharField(max_length=200, null=True, verbose_name='Driver Name')),
                ('brand', models.CharField(max_length=200, null=True, verbose_name='Car Brand')),
                ('Insurance_comp', models.CharField(max_length=200, null=True, verbose_name='Insurance Company')),
                ('service_comp', models.CharField(max_length=200, null=True, verbose_name='Service Company')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.CharField(max_length=200, null=True, verbose_name='Loan_Amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('interest_rate', models.CharField(max_length=200, null=True, verbose_name='Rate Of Interest')),
                ('status', models.CharField(choices=[('Performing', 'Performing'), ('Late', 'Late'), ('Overdue', 'Overdue'), ('Default', 'Default'), ('Paid', 'Paid')], max_length=200, null=True, verbose_name='Status Of Loan')),
                ('Tags', models.ManyToManyField(to='sacco.tag')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sacco.sacco_member')),
            ],
        ),
    ]
