# Generated by Django 4.1.3 on 2022-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sacco_official',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='sacco_member',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='sacco_member',
            name='driver_first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='sacco_member',
            name='driver_second_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Second Name'),
        ),
        migrations.AddField(
            model_name='sacco_official',
            name='second_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Offial Name'),
        ),
    ]
