# Generated by Django 4.1.3 on 2022-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_remove_vehicle_driver_name_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco_member',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
