# Generated by Django 4.1.3 on 2022-12-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0006_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(choices=[('Chaka', 'Chaka'), ('Kingongo', 'Kingongo'), ('Kirichu', 'Kirichu'), ('Kiganjo', 'Kiganjo')], max_length=200, null=True, verbose_name='Name'),
        ),
    ]
