# Generated by Django 4.1.3 on 2022-12-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0007_alter_destination_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
