# Generated by Django 4.1.3 on 2022-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0008_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Your Name')),
                ('vehicle_num_plate', models.CharField(max_length=200, null=True, verbose_name='Vehicle No. Plate')),
                ('subject', models.CharField(max_length=400, null=True, verbose_name='Subject')),
                ('message', models.CharField(max_length=1000, null=True, verbose_name='Your Complaint')),
            ],
        ),
    ]
