# Generated by Django 4.1.3 on 2022-12-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0009_complaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
    ]
